### PR TITLE
Added possibility to translate ScpDriverInstaller

### PR DESCRIPTION
**Pull request by charlesmilette**
Also added French locale.
If you want to generate a `Resources.resx` file with english summaries, delete the file `Resources.Designer.cs` from Windows Explorer, make an edit to the `Resources.resx` file from Visual Studio and save. `Resources.Designer.cs` should then be regenerated with the current machine's locale for the summaries. If you don't want to keep the changes to `Resources.resx`, simply cancel them from Visual Studio and save the file, `Resources.Designer.cs` should persist.

See the translation [here](https://youtu.be/kRjduKR281o)

### CODE REVIEW

**Comment by charlesmilette** [comment]
I'll drop @nefarius here, since he doesn't seem to have noticed there was a PR.

**Comment by nefarius** [comment]
Oh I sure did notice, but I was sick the last couple of days so I'm slowly catching up on all the e-mails.

**Comment by charlesmilette** [comment]
I didn't knew. Sorry for bothering.

**Comment by nefarius** [comment]
Thank you very much :+1:

**Comment by charlesmilette** [comment]
I also plan to add it on some other parts, but that will not be for now, since I clean installed my computer and reinstalling VS is not in my priorities.

I'll wait for VS 15 and then I'll install it.

**Comment by nefarius** [comment]
I'm currently installing VS 2015 **Update 2**. I'm still working with 2013 on the project since it's stable and all my extensions work within it. Might try to fully migrate to 2015 if some bugs have been fixed by M$ and all my extensions work as good as in 2013.

**Comment by charlesmilette** [comment]
On the video, it __was__ Vs 2015 Update 2.

Visual Studio 2015 is Visual Studio version 14.

Visual Studio version 15 is the new version, currently in preview. I'll wait for a stable release

**Comment by nefarius** [comment]
Ah I see. I personally prefer to linger with the older versions since software of this magnitude tends to be more buggy the younger it is.

**Comment by charlesmilette** [comment]
I'm an Insider, so I sure know how to live with bugs. :laughing:

**Pull request merged**
