### PR TITLE
Added custom color support for battery status (DS4).

### PR DESCRIPTION
**Pull request by chrizonix**
Hi nefarius,

I've added custom color support for the battery status for the DS4.
I've only changed some configs (in ScpControl), and added the corresponding logic in BthDs4.cs.
I've also added the required properties to the ScpSettings project.

Feel free to review my changes.
If you would like to change some code guidelines, or naming conventions, let me know.

The source code for the Color Picker is used from [here (codeproject)](https://www.codeproject.com/Articles/131708/WPF-Color-Picker-Construction-Kit).
I've modified the design of this color picker to match the dark metro theme ([ColorPickerDarkTheme.zip](https://github.com/nefarius/ScpToolkit/files/755903/ColorPickerDarkTheme.zip)).

screenshot

Best regards
Chris

PS: I've seen your domain ends with "at". I'm also from Austria, Greetings buddy :)

### CODE REVIEW

**Comment by charlesmilette** [comment]
✨

**Comment by chrizonix** [comment]
Fixed merge conflicts :)

**Comment by axbmcuser** [comment]
@chrizonix Great feature idea. Is there a chance getting a new installer from you? Doesn't look like the there will be any new release installers. Thank you! :)

**Comment by chrizonix** [comment]
@axbmcuser Here you go :)

https://github.com/chrizonix/ScpToolkit/releases/tag/v1.7.277.170526

**Comment by axbmcuser** [comment]
Many thanks!! Question: Does the update also contain all other changes from github which were merged after the last installer got released? (v1.7.277.16103) Thanks again! :)

**Comment by chrizonix** [comment]
@axbmcuser No, but there weren't any major updates (no new features), only a renaming of a slider, and a fix for the profile manager (which I don't use). But if you want, I can recompile the whole project, to include all updates, but I think it's not necessary.

**Comment by axbmcuser** [comment]
@chrizonix
Thanks for the details. If it isn't too much trouble i'd very welcome a complete compile. 
But as said, i'm thankful with and without! :)

**Comment by chrizonix** [comment]
@axbmcuser Although there are no new features. Here is the latest build.
https://github.com/chrizonix/ScpToolkit/releases/tag/v1.7.277.170611

**Comment by axbmcuser** [comment]
Again, thanks! Did not install it yet, but great to have a somehow "final" full installer prepared for my upcoming reinstall! :)

**Comment by chrizonix** [comment]
@axbmcuser There is no need for a reinstall, because I only released a zip file. Just copy my files over your existing installation.

@OT
I have never used DS3 with the controller ID option. I've always used the battery status indication. So no I have never experience this behavior.

**Pull request merged**
